// Generated from the project image set — do not edit by hand.
export type MediaAsset = { src: string; width: number; height: number; blurDataURL: string };

export const media = {
  "hero-interior": { src: "/images/hero-interior.webp", width: 2400, height: 1350, blurDataURL: "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADQAQCdASoOAAgAA4BaJQBOgCF5Zj2pwAD+vo03E3Rbay7a5nSYTrGu4udOI+3NB548BK+INEFSPJUO5PapBOajMFq02kBJYGwBdIWBAHj32u1eZAAAAA==" },
  "og-cover": { src: "/images/og-cover.webp", width: 1200, height: 630, blurDataURL: "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADwAQCdASoOAAcAA4BaJYgCdAEUPf5LnAAA/qsyuwO1mFex5V/Plp/M+Lbx+EO2FcuMVKY7ZuVQlPSlovBsBrYjyWh+sJU/qN11SRF8afwAAA==" },
  "barber-marcus": { src: "/images/barber-marcus.webp", width: 900, height: 1200, blurDataURL: "data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAADwAwCdASoOABMAPu1iqU2ppaOiMAgBMB2JZQC7ABh7hVYzv6/3jTkAAP4nczFc1pCl01ddiZibK+BY3RBu6pI6YXHmd1yBfzkaf1NKv52gOiF43pXVIsAuDohHVY5GYyVFFY/PdHuDr/duwysRTa1ei6MBuY0VwAA=" },
  "barber-elias": { src: "/images/barber-elias.webp", width: 900, height: 1200, blurDataURL: "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAABwBACdASoOABMAPu1iqU2ppaOiMAgBMB2JQBOmUGSy9t4gVMfBOye6JTQPIAD8+IxEzFKchSAgTGFVJ7GmP6BG9ikFUahWvakHaEjqx0YpDSz1BaJu17sKfurixUayAfC20k/qTYscHtThWJCuLFpvDX5ct8Ve2N4yLge79DcNctIxu4PKDQgI8oUtisI7GZT8Ss2tAAA=" },
  "barber-deniz": { src: "/images/barber-deniz.webp", width: 900, height: 1200, blurDataURL: "data:image/webp;base64,UklGRrQAAABXRUJQVlA4IKgAAAAwBACdASoOABMAPu1iqU2ppaOiMAgBMB2JQBhT+ABQW4pQdEaD9AFC/oAA/tFEvChkZIRrVz5NNWz9yvQVznKjqe4zvI95W3IbloV1TRXQhJE65N+2Z001PIUuE1IqMlLQY6qFE9GsJAHrISon0PQjVawwsSgARuny0gF5ZzHCPN0w0j61YJE4c83DqmKpjh1dygFGocYZNY6knS2RMnne3OaH6RlrQAA=" },
  "barber-jonah": { src: "/images/barber-jonah.webp", width: 900, height: 1200, blurDataURL: "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAAAwBACdASoOABMAPu1iqU2ppaOiMAgBMB2JQBUeg+TxoUfr3WQTYEstPeAA/tAky2ijCvDmnsF/s98t9Z2skyxpC4D72nqkJtwjLn4aS+xraS9lNdFvmqcwjQuQzTWwQMyrwbYX0fdTlv4EvEQtmOZfoIBLdDoRTTVIunPGf1l2/Rj7jXnXZ6JElllkQAAA" },
  "about-craft": { src: "/images/about-craft.webp", width: 1000, height: 1333, blurDataURL: "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAADwAwCdASoOABMAPu1iqU2ppaOiMAgBMB2JYwCuHBjMt5djrshD/jVAAP7qupmGLSXOfyG+PBoArc5sLK3wB+7qf7C9IW9cXBKA4KDSApgTu2LgqzOPD2LlHu0g9AIwWwxuALd0XVXluPB/y+kxbQpMWr6OuONUbIAAAA==" },
  "cut-skin-fade": { src: "/images/cut-skin-fade.webp", width: 1000, height: 1333, blurDataURL: "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAAAwBACdASoOABMAPu1iqU2ppaOiMAgBMB2JQBb3BAt73jR7zkQ4FeOvauAA/rbtcjdqmrcoL+E7X+Q8oAEBhcfp2VzS/oQevzVQcSaWv4HoGNU9sxgHLBCinO56S5T2AO5H26F3EFLcUTg9nxlhqADyHQJXfl91z+0AAA==" },
  "cut-texture": { src: "/images/cut-texture.webp", width: 1000, height: 1333, blurDataURL: "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAAAQBACdASoOABMAPu1iqU2ppaOiMAgBMB2JYwC+SBosfWEX0mUSdzCMAAD+05N4kUAwJSEAI6VYvmTC6u/4WI/P0mInkZosCFdpQcuV/0FW13FIH+PFelA40p+hzTSigocDCiMJQUVRpeBFdsiWnsAA" },
  "cut-beard": { src: "/images/cut-beard.webp", width: 1100, height: 1100, blurDataURL: "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAAAQAgCdASoOAA4AA4BaJQBOgCF56dAFeUIAAPw6dJd9+eq3FoTMrkqteOYNznCquUPt1y7hsSJ5DbyEWkaW7uhvDSPws3IkadhCdvmxMQ3Z222zhK2VvNDGSAySVWkIDAAAAA==" },
  "cut-classic": { src: "/images/cut-classic.webp", width: 1400, height: 1050, blurDataURL: "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAwAgCdASoOAAsAA4BaJZQC7AECm68hiFdEAAD+rNK8tRpXJhvKtOTys7EDziYeQDejd/uKKGnnQ5PyXmpZcGM6o2Du06rAI/GjC5aZwPssOLVz/0WN6OAF65fYAA==" },
  "cut-shave": { src: "/images/cut-shave.webp", width: 1400, height: 1050, blurDataURL: "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAAAQAgCdASoOAAsAA4BaJYgCdADwnrAYGNqAAP7ysN9aSZxwOE74Zr6HloFCi0jL1eqT3fWUDU0ffANDrxYnChkXo5p4MK9QTp6WwpyfmW1AuIrfnRSs0IlygAA=" },
  "ba-fade-before": { src: "/images/ba-fade-before.webp", width: 900, height: 1013, blurDataURL: "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAABQAgCdASoOABAAA4BaJQBOgMXI4JbYQgFwjIAA/u6eosOgj0Hj/J/eSNZxIn3CQJ+Mp4gHpgm8sMHfOLu+xpkGNGE/2parHth9izq8Qp29TaB7ij7K0QcBdHRsuDI9/MHcAA==" },
  "ba-fade-after": { src: "/images/ba-fade-after.webp", width: 900, height: 1013, blurDataURL: "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAAAQAgCdASoOABAAA4BaJQBOgCPcN4+eL7ZAAP7snYSMGyRAqtqgQ/6gX2x0JjPCrdCGEgM83te1sYTbnleF4KaQ0GXCZC3wBlan1O+PWkXOv/38yAJkkavowRDeOLsUL7tSQgkJ6W1i4yYAAAA=" },
  "ba-classic-before": { src: "/images/ba-classic-before.webp", width: 900, height: 1013, blurDataURL: "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAwAgCdASoOABAAA4BaJYwCdH8AFwEpk81FwADup4zVv6AycP2LaNe1MnGo/p51gC+dEfffVGgLOEZgZ4zlmSRrTltRUyC0Kai/ouWWlfZdFQYXewJxAAAA" },
  "ba-classic-after": { src: "/images/ba-classic-after.webp", width: 900, height: 1013, blurDataURL: "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAABQAgCdASoOABAAA4BaJQBOgMX15vSCZmEfQPAA/ugrxH4+7IPaS+KAayxXMCgrmJ2D9ymA/fJNmDQxtP1Lxp0vGatvj1TVPkx0ayfliNgwlp+izXxpRyDsD1pAsiJNafpq/cRd9EYaQlj+yAA=" },
} satisfies Record<string, MediaAsset>;

export type MediaKey = keyof typeof media;
