import type {
  AppNotification,
  AppointmentStatus,
  Business,
  CustomerProfile,
  Dispute,
  DisputeKind,
  OpenSlot,
  PlatformSettings,
  Service,
  Staff,
  UUID,
} from "../types";

/**
 * Every mutation in NOW is expressed as one of these actions.
 *
 * Two properties matter:
 *  1. The reducer is pure, so the action log can be replayed to restore a
 *     session exactly (that is how persistence works — see `provider.tsx`).
 *  2. Each action maps cleanly onto one future API call / Supabase mutation,
 *     which is why ids are generated by the caller rather than the reducer.
 */
export type Action =
  | { type: "tick"; now: number }
  /* Availability -------------------------------------------------------- */
  | {
      type: "slot/hold";
      slot_id: UUID;
      customer_id: UUID;
      held_until: string;
    }
  | { type: "slot/release"; slot_id: UUID }
  | {
      type: "slot/publish";
      slot: Omit<OpenSlot, "created_at" | "updated_at"> & { created_at?: string };
    }
  | { type: "slot/unpublish"; slot_id: UUID }
  | { type: "slot/view"; slot_id: UUID }
  /* Bookings ------------------------------------------------------------ */
  | {
      type: "appointment/book";
      appointment_id: UUID;
      appointment_service_id: UUID;
      payment_id: UUID;
      notification_ids: [UUID, UUID];
      thread_id: UUID;
      message_id: UUID;
      reference: string;
      slot_id: UUID;
      customer_id: UUID;
      customer_note: string | null;
      created_at: string;
    }
  | {
      type: "appointment/create";
      appointment_id: UUID;
      appointment_service_id: UUID;
      business_id: UUID;
      customer_id: UUID;
      staff_id: UUID;
      service_id: UUID;
      date: string;
      start_time: string;
      reference: string;
      created_at: string;
      business_note: string | null;
    }
  | {
      type: "appointment/cancel";
      appointment_id: UUID;
      by: "customer" | "business";
      reason: string;
      at: string;
      notification_id: UUID;
      /** Re-publish the freed time as an opening. */
      republish_slot_id: UUID | null;
    }
  | { type: "appointment/status"; appointment_id: UUID; status: AppointmentStatus; at: string }
  | { type: "appointment/note"; appointment_id: UUID; business_note: string }
  /* Reviews ------------------------------------------------------------- */
  | {
      type: "review/create";
      review_id: UUID;
      appointment_id: UUID;
      rating: 1 | 2 | 3 | 4 | 5;
      body: string;
      photo_seeds: string[];
      created_at: string;
    }
  | { type: "review/reply"; review_id: UUID; body: string; at: string }
  | { type: "review/report"; review_id: UUID; reason: string }
  | { type: "review/hide"; review_id: UUID; hidden: boolean }
  /* Relationships ------------------------------------------------------- */
  | { type: "favorite/toggle"; favorite_id: UUID; customer_id: UUID; business_id: UUID; at: string }
  | { type: "favorite/alerts"; business_id: UUID; customer_id: UUID; enabled: boolean }
  /* Messaging ----------------------------------------------------------- */
  | {
      type: "message/send";
      message_id: UUID;
      thread_id: UUID;
      /** Provided when the thread may not exist yet. */
      thread_seed: { business_id: UUID; customer_id: UUID; appointment_id: UUID | null } | null;
      sender_role: "customer" | "business";
      sender_id: UUID | null;
      body: string;
      at: string;
    }
  | { type: "message/read"; thread_id: UUID; role: "customer" | "business" }
  /* Notifications ------------------------------------------------------- */
  | { type: "notification/read"; notification_id: UUID; at: string }
  | { type: "notification/read-all"; user_id: UUID; at: string }
  | { type: "notification/create"; notification: AppNotification }
  /* Business management ------------------------------------------------- */
  | { type: "service/upsert"; service: Service }
  | { type: "service/delete"; service_id: UUID }
  | { type: "staff/upsert"; staff: Staff; service_ids: UUID[] }
  | { type: "staff/delete"; staff_id: UUID }
  | { type: "business/update"; business_id: UUID; patch: Partial<Business> }
  | {
      type: "business/hours";
      business_id: UUID;
      day_of_week: number;
      opens_at: string | null;
      closes_at: string | null;
      is_closed: boolean;
    }
  /* Accounts ------------------------------------------------------------ */
  | { type: "profile/update"; user_id: UUID; patch: Partial<CustomerProfile> }
  | { type: "user/update"; user_id: UUID; patch: { full_name?: string; email?: string; phone?: string } }
  /* Safety & admin ------------------------------------------------------ */
  | {
      type: "dispute/create";
      dispute_id: UUID;
      kind: DisputeKind;
      appointment_id: UUID | null;
      business_id: UUID | null;
      customer_id: UUID | null;
      review_id: UUID | null;
      opened_by_role: Dispute["opened_by_role"];
      reason: string;
      detail: string;
      at: string;
    }
  | {
      type: "dispute/resolve";
      dispute_id: UUID;
      status: Dispute["status"];
      note: string;
      at: string;
    }
  | { type: "admin/settings"; patch: Partial<PlatformSettings>; at: string }
  | { type: "admin/business-status"; business_id: UUID; status: Business["status"] }
  | {
      type: "admin/verification";
      business_id: UUID;
      status: Business["verification_status"];
      note: string | null;
      at: string;
    }
  | { type: "admin/category-toggle"; category_id: UUID; is_active: boolean };

/** Actions that should never be replayed from storage (they are ephemeral). */
export const TRANSIENT_ACTIONS = new Set<Action["type"]>(["tick", "slot/view"]);
