'use client';

import { useActionState, useRef, useState } from 'react';
import { Play, Volume2 } from 'lucide-react';
import {
  DISCLOSURE_OPTIONS,
  LANGUAGE_OPTIONS,
  LENGTH_OPTIONS,
  PACE_OPTIONS,
  PERSONALITY_PRESETS,
  availableVoices,
  defaultGreeting,
} from '@afd/shared';
import { Alert, Button, Field, Input, Select, Switch, Textarea, cn } from '@/components/ui';
import { saveAgentAction } from '@/server/actions';
import type { ActionResult } from '@/lib/errors';

interface Initial {
  display_name: string;
  voice: string;
  language: string;
  personality: string;
  speaking_pace: string;
  response_length: string;
  greeting: string;
  instructions: string;
  transfer_enabled: boolean;
  transfer_phone: string;
  sms_enabled: boolean;
  appointment_booking_enabled: boolean;
  photo_requests_enabled: boolean;
  disclosure_setting: string;
  fallback_phone: string;
}

/**
 * Receptionist configuration.
 *
 * Every control here maps to a real field that changes what the AI does on the
 * next call — there are no cosmetic sliders. The voice preview plays audio
 * generated by the same provider that answers calls.
 */
export function ReceptionistForm({
  initial,
  canEdit,
  organizationName,
}: {
  initial: Initial;
  canEdit: boolean;
  organizationName: string;
}) {
  const [state, action, pending] = useActionState<ActionResult | null, FormData>(saveAgentAction, null);

  const [voice, setVoice] = useState(initial.voice);
  const [agentName, setAgentName] = useState(initial.display_name);
  const [greeting, setGreeting] = useState(initial.greeting);
  const [transferEnabled, setTransferEnabled] = useState(initial.transfer_enabled);
  const [smsEnabled, setSmsEnabled] = useState(initial.sms_enabled);
  const [bookingEnabled, setBookingEnabled] = useState(initial.appointment_booking_enabled);
  const [photosEnabled, setPhotosEnabled] = useState(initial.photo_requests_enabled);

  const [previewing, setPreviewing] = useState<string | null>(null);
  const [previewError, setPreviewError] = useState<string | null>(null);
  const [previewNotice, setPreviewNotice] = useState<string | null>(null);
  const audioRef = useRef<HTMLAudioElement | null>(null);

  const fields = state?.fields ?? {};
  const voices = availableVoices();

  async function preview(voiceId: string) {
    setPreviewing(voiceId);
    setPreviewError(null);
    setPreviewNotice(null);
    try {
      const res = await fetch('/api/receptionist/voice-preview', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ voice: voiceId, text: greeting.slice(0, 260) }),
      });
      if (!res.ok) {
        const json = await res.json().catch(() => null);
        setPreviewError(json?.error?.message ?? 'The preview could not be generated.');
        return;
      }
      if (res.headers.get('x-demo-audio') === 'true') {
        setPreviewNotice(
          'Demo mode is on, so this is a silent placeholder rather than a real voice sample. Add OPENAI_API_KEY to hear the actual voice.',
        );
      }
      const blob = await res.blob();
      const url = URL.createObjectURL(blob);
      if (audioRef.current) {
        audioRef.current.src = url;
        await audioRef.current.play();
      }
    } catch {
      setPreviewError('The preview could not be played.');
    } finally {
      setPreviewing(null);
    }
  }

  return (
    <form action={action} className="space-y-6">
      {state?.ok && <Alert tone="positive" title={state.message ?? 'Saved'} />}
      {state && !state.ok && (
        <Alert tone="critical" title={state.message ?? 'That did not save'}>
          {state.action && <p>{state.action}</p>}
        </Alert>
      )}

      <div className="grid gap-4 sm:grid-cols-2">
        <Field
          label="Receptionist name"
          htmlFor="display_name"
          required
          hint="What it calls itself on the phone."
          error={fields.display_name}
        >
          <Input
            name="display_name"
            value={agentName}
            onChange={(e) => setAgentName(e.target.value)}
            disabled={!canEdit}
            required
          />
        </Field>

        <Field label="Language" htmlFor="language">
          <Select name="language" defaultValue={initial.language} disabled={!canEdit}>
            {LANGUAGE_OPTIONS.map((l) => (
              <option key={l.id} value={l.id}>
                {l.label}
              </option>
            ))}
          </Select>
        </Field>
      </div>

      <Field
        label="Greeting"
        htmlFor="greeting"
        required
        hint="The first thing every caller hears."
        error={fields.greeting}
      >
        <Textarea
          name="greeting"
          value={greeting}
          onChange={(e) => setGreeting(e.target.value)}
          rows={2}
          disabled={!canEdit}
          required
        />
      </Field>

      {canEdit && (
        <button
          type="button"
          className="text-sm font-medium text-brand-600 hover:underline"
          onClick={() => setGreeting(defaultGreeting(organizationName, agentName || 'Mia'))}
        >
          Reset to the suggested greeting
        </button>
      )}

      {/* Voice picker ---------------------------------------------------- */}
      <fieldset>
        <legend className="text-sm font-medium text-ink">Voice</legend>
        <p className="mt-1 text-xs text-ink-subtle">
          Press play to hear each voice read your greeting.
        </p>
        <input type="hidden" name="voice" value={voice} />

        {previewError && <Alert tone="critical" title={previewError} className="mt-3" />}
        {previewNotice && <Alert tone="caution" title="Demo preview" className="mt-3">{previewNotice}</Alert>}

        <div className="mt-3 grid gap-2 sm:grid-cols-2">
          {voices.map((v) => (
            <div
              key={v.id}
              className={cn(
                'flex items-start justify-between gap-3 rounded-lg border p-3 transition-colors',
                voice === v.id ? 'border-brand-600 bg-brand-50' : 'border-line bg-surface',
              )}
            >
              <label className="flex min-w-0 flex-1 cursor-pointer items-start gap-2.5">
                <input
                  type="radio"
                  name="voice_choice"
                  checked={voice === v.id}
                  onChange={() => setVoice(v.id)}
                  disabled={!canEdit}
                  className="mt-1 size-4 text-brand-600"
                />
                <span className="min-w-0">
                  <span className="block text-sm font-medium text-ink">{v.label}</span>
                  <span className="block text-xs text-ink-subtle">{v.description}</span>
                </span>
              </label>
              <Button
                type="button"
                size="icon"
                variant="secondary"
                aria-label={`Preview the ${v.label} voice`}
                loading={previewing === v.id}
                onClick={() => preview(v.id)}
              >
                {previewing === v.id ? <Volume2 aria-hidden /> : <Play aria-hidden />}
              </Button>
            </div>
          ))}
        </div>
        <audio ref={audioRef} className="sr-only" />
      </fieldset>

      <div className="grid gap-4 sm:grid-cols-3">
        <Field label="Personality" htmlFor="personality">
          <Select name="personality" defaultValue={initial.personality} disabled={!canEdit}>
            {PERSONALITY_PRESETS.map((p) => (
              <option key={p.id} value={p.id}>
                {p.label}
              </option>
            ))}
          </Select>
        </Field>
        <Field label="Speaking pace" htmlFor="speaking_pace">
          <Select name="speaking_pace" defaultValue={initial.speaking_pace} disabled={!canEdit}>
            {PACE_OPTIONS.map((p) => (
              <option key={p.id} value={p.id}>
                {p.label}
              </option>
            ))}
          </Select>
        </Field>
        <Field label="Reply length" htmlFor="response_length">
          <Select name="response_length" defaultValue={initial.response_length} disabled={!canEdit}>
            {LENGTH_OPTIONS.map((l) => (
              <option key={l.id} value={l.id}>
                {l.label}
              </option>
            ))}
          </Select>
        </Field>
      </div>

      <Field
        label="Extra instructions"
        htmlFor="instructions"
        hint="Anything else the receptionist should know. Added to every call."
        error={fields.instructions}
      >
        <Textarea name="instructions" defaultValue={initial.instructions} rows={3} disabled={!canEdit} />
      </Field>

      <Field label="AI disclosure" htmlFor="disclosure_setting">
        <Select name="disclosure_setting" defaultValue={initial.disclosure_setting} disabled={!canEdit}>
          {DISCLOSURE_OPTIONS.map((d) => (
            <option key={d.id} value={d.id}>
              {d.label}
            </option>
          ))}
        </Select>
      </Field>
      <p className="-mt-3 text-xs text-ink-subtle">
        Whichever you choose, the receptionist always answers truthfully when a caller asks whether
        it is a person. It will never claim to be human.
      </p>

      {/* Capabilities ---------------------------------------------------- */}
      <fieldset className="divide-y divide-line rounded-lg border border-line px-4">
        <legend className="px-1 text-sm font-medium text-ink">What it is allowed to do</legend>

        <Switch
          id="appointment_booking_enabled"
          label="Book appointments"
          description="Checks real availability, then creates the appointment."
          checked={bookingEnabled}
          onChange={setBookingEnabled}
          disabled={!canEdit}
        />
        <input type="hidden" name="appointment_booking_enabled" value={bookingEnabled ? 'on' : 'off'} />

        <Switch
          id="sms_enabled"
          label="Send text messages"
          description="Confirmations and follow-ups to the caller."
          checked={smsEnabled}
          onChange={setSmsEnabled}
          disabled={!canEdit}
        />
        <input type="hidden" name="sms_enabled" value={smsEnabled ? 'on' : 'off'} />

        <Switch
          id="photo_requests_enabled"
          label="Request photos"
          description="Texts a secure, expiring upload link when photos would help."
          checked={photosEnabled && smsEnabled}
          onChange={setPhotosEnabled}
          disabled={!canEdit || !smsEnabled}
        />
        <input type="hidden" name="photo_requests_enabled" value={photosEnabled ? 'on' : 'off'} />

        <Switch
          id="transfer_enabled"
          label="Transfer calls to a person"
          description="Hands the caller over when they ask, or when your rules say so."
          checked={transferEnabled}
          onChange={setTransferEnabled}
          disabled={!canEdit}
        />
        <input type="hidden" name="transfer_enabled" value={transferEnabled ? 'on' : 'off'} />
      </fieldset>

      <div className="grid gap-4 sm:grid-cols-2">
        <Field
          label="Transfer number"
          htmlFor="transfer_phone"
          required={transferEnabled}
          hint="Where callers are sent when they ask for a person."
          error={fields.transfer_phone}
        >
          <Input
            name="transfer_phone"
            defaultValue={initial.transfer_phone}
            inputMode="tel"
            placeholder="(215) 555-0100"
            disabled={!canEdit || !transferEnabled}
          />
        </Field>
        <Field
          label="Fallback number"
          htmlFor="fallback_phone"
          hint="Used if the AI itself cannot answer. Callers are forwarded here rather than dropped."
          error={fields.fallback_phone}
        >
          <Input
            name="fallback_phone"
            defaultValue={initial.fallback_phone}
            inputMode="tel"
            disabled={!canEdit}
          />
        </Field>
      </div>

      {canEdit && (
        <Button type="submit" size="lg" loading={pending}>
          {pending ? 'Saving' : 'Save receptionist settings'}
        </Button>
      )}
    </form>
  );
}
