/* ============================================================================
 * ADOPT REAL IMAGERY
 * ----------------------------------------------------------------------------
 * Drop real photographs into public/images/art named after their slot id —
 * hero-primary.jpg, service-nails.webp, gallery-03.avif — then run:
 *
 *   npm run images:adopt
 *
 * It maintains a single clearly-marked override block at the bottom of
 * src/lib/images.ts pointing each adopted slot at its real file. Slots without
 * a photograph keep their generated placeholder art.
 *
 * Safe to run repeatedly: the block is rewritten from scratch every time, so
 * replacing hero-primary.jpg with hero-primary.webp updates cleanly and
 * deleting a photo reverts that slot to its placeholder.
 * ========================================================================== */

import { readdirSync, readFileSync, writeFileSync, existsSync, rmSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const artDir = resolve(root, "public/images/art");
const manifestPath = resolve(root, "src/lib/images.ts");

const START = "/* --- ADOPTED IMAGERY — generated by scripts/adopt-images.mjs --- */";
const END = "/* --- END ADOPTED IMAGERY --- */";

if (!existsSync(artDir)) {
  console.error("public/images/art does not exist. Run `npm run images:placeholders` first.");
  process.exit(1);
}

let manifest = readFileSync(manifestPath, "utf8");

/* Which slot ids actually exist in the manifest. */
const declared = new Set(
  [...manifest.matchAll(/slot\(\s*"([a-z0-9-]+)"/g)].map((m) => m[1]),
);

/* Photographic files win over the .svg placeholders. Prefer modern formats
   when a slot has been delivered more than once. */
const PREFERENCE = ["avif", "webp", "jpg", "jpeg", "png"];
const found = new Map();

for (const file of readdirSync(artDir)) {
  const match = /^([a-z0-9-]+)\.(avif|webp|jpg|jpeg|png)$/i.exec(file);
  if (!match) continue;

  const [, id, rawExt] = match;
  const ext = rawExt.toLowerCase();

  if (!declared.has(id)) {
    console.warn(`  ! ${file} — no slot called "${id}" in images.ts, skipping`);
    continue;
  }

  const existing = found.get(id);
  if (!existing || PREFERENCE.indexOf(ext) < PREFERENCE.indexOf(existing.ext)) {
    found.set(id, { file, ext });
  }
}

/* Rebuild the override block from scratch. */
const adopted = [...found.entries()].sort(([a], [b]) => a.localeCompare(b));

const block =
  adopted.length === 0
    ? ""
    : [
        "",
        START,
        "// Edit by re-running the script, not by hand — this block is regenerated.",
        ...adopted.map(
          ([id, { file }]) => `IMAGES["${id}"].src = "/images/art/${file}";`,
        ),
        END,
        "",
      ].join("\n");

/* Strip any previous block, then insert the new one before the accessor. */
const blockRe = new RegExp(
  `\\n*${START.replace(/[.*+?^${}()|[\]\\/]/g, "\\$&")}[\\s\\S]*?${END.replace(
    /[.*+?^${}()|[\]\\/]/g,
    "\\$&",
  )}\\n*`,
  "m",
);

manifest = manifest.replace(blockRe, "\n");

const anchor = "\nexport function image(";
if (!manifest.includes(anchor)) {
  console.error("Could not find the `image()` accessor in images.ts — aborting.");
  process.exit(1);
}

manifest = manifest.replace(anchor, `${block}${anchor}`);
writeFileSync(manifestPath, manifest, "utf8");

/* next/image keys its optimised output on the request URL, not on the source
   file's contents — so replacing a photograph at the same filename keeps
   serving the old bytes until this cache is dropped. Silently confusing, and
   it burned us once, so clear it every time. */
const imageCache = resolve(root, ".next/cache/images");
if (existsSync(imageCache)) {
  rmSync(imageCache, { recursive: true, force: true });
  console.log("Cleared .next/cache/images so replaced files are re-optimised.\n");
}

if (adopted.length === 0) {
  console.log("No photographic files in public/images/art — every slot is on placeholder art.");
} else {
  console.log(`Adopted ${adopted.length} of ${declared.size} slots:\n`);
  for (const [id, { file }] of adopted) console.log(`  ${id.padEnd(22)} → ${file}`);
  console.log(`\n${declared.size - adopted.length} slot(s) still on placeholder art.`);
}
